export { DashboardMockup } from './DashboardMockup'
export { MockupSidebar } from './MockupSidebar'
export { MockupPageLayout } from './MockupPageLayout'
export { SampleQueueHeader } from './SampleQueueHeader'
export { SampleQueueTable } from './SampleQueueTable'
export { OrdenesView } from './OrdenesView'
export { PacientesView } from './PacientesView'
export { ResultadosView } from './ResultadosView'
export { StatusBadge } from './StatusBadge'
export { MOCKUP_NAV_ITEMS, SAMPLE_QUEUE_ROWS } from './mockup-data'
export type { MockupNavItem, MockupViewId, SampleQueueRow } from './types'
